### ISSUE TITLE
Match string or null

### ISSUE THREAD

**Issue by marocchino** [WhitePayments/match_json#6]
I will be happy if I can use `include_json`  like this:

``` ruby
    it 'passes when key has null or string' do
      [ #      actual json                               match string
        [%Q([{ "one": null  }, { "one": "aaa" }]), %Q([{ "one": {string|null} }])],
        [%Q([{ "one": "bbb" }, { "one": "aaa" }]), %Q([{ "one": {string|null} }])],
        [%Q([{ "one": "aaa" }, { "one": null  }]), %Q([{ "one": {string|null} }])],
        [%Q([{ "one": null  }, { "one": null  }]), %Q([{ "one": {string|null} }])],
      ].each do |actual, matcher|
        expect(actual).to include_json(matcher)
      end
    end

    it 'fails when key has not accepted type' do
      [ #      actual json                               match string
        [%Q([{ "one": null  }, { "one": 1 }]), %Q([{ "one": {string|null} }])],
        [%Q([{ "one": "bbb" }, { "one": 1 }]), %Q([{ "one": {string|null} }])],
      ].each do |actual, matcher|
        expect(actual).not_to include_json(matcher)
      end
    end
```

but, I think, `{key1|key2}` style could be confused for someone. Do you have any idea for this?

**Comment by alovak** [comment]
Are you going to use {string|null} because api will randomly return different values? Or it's just because you want to use the same piece of json in different tests (copy/paste)?

As for me I usually test only certain keys/values and I know what exactly should be there.

To avoid duplication and test json document in general (not for values, but for structure and types) we use json-schema-validator. I have more detailed desciption of how to do this here: http://stackoverflow.com/questions/13955233/how-to-test-a-json-rest-api/29180337#29180337

json schema is the place where you can describe the type of the value and you can specify multiple types like this:

```
    "email": {
      "type": ["string", "null"]
    }
```

but to test values in different cases this approach is not suitable and that is why match_json exists :)

**Comment by marocchino** [comment]
> Are you going to use {string|null} because api will randomly return different values?

Yes. It's part of spec. ;_;
Maybe, I should mock those object, and separate test. Thank you your advice.
